/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 /Users/kennethchoi/Documents/Dev/_/motion/threejs/misc/configurator/nike/nike01/public/assets/models/AF1_v2.glb 
*/

import React, { useEffect, useMemo, useRef } from 'react';
import { useGLTF, useKTX2, useTexture } from '@react-three/drei';

import baseColor from '../assets/textures/base_color-astc_leather.webp';
// import normal from '/assets/textures/normal-astc_leather.ktx?url';
// import orm from '/assets/textures/orm-astc_leather.ktx?url';
import groundShadow from '../assets/textures/ground_shadow-astc.webp';
import { useLoader } from '@react-three/fiber';
import * as THREE from 'three';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/assets/models/AF1_v2.glb');
  const groundShadowTexture = useTexture(groundShadow);
  const baseColorTexture = useTexture(baseColor);

  const material = useMemo(
    () =>
      new THREE.MeshStandardMaterial({
        map: baseColorTexture,
        // normalMap: normalTexture,
        // normalScale: [1, 1],
        // aoMap: ormTexture,
        // aoMapIntensity: 1,
        // envMapIntensity: 1,
        // displacementMap: ormTexture,
        // displacementScale: 0.1,
        // metalness: 0.5,
        // roughness: 0.5,
        // envMapIntensity: 1,
        // envMap: envMapTexture,
        // envMapIntensity: 1,
      }),
    []
  );

  useEffect(() => {
    console.log(nodes, materials);
    // console.log(groundShadowTexture);
    // console.log(baseColor);
  }, []);

  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, Math.PI * 0.5]}>
        <mesh
          geometry={nodes.shadow_plane.geometry}
          // material={materials.shadow_plane}
        >
          <meshStandardMaterial
            map={groundShadowTexture}
            color={0xffffff}
            transparent
            opacity={0.5}
          />
        </mesh>
        <group position={[-0.75, -0.75, -0.55]} rotation={[0, -0.262, 0]}>
          <mesh
            geometry={nodes.lf_backstay.geometry}
            material={materials.backtab_01}
          />
          <mesh
            geometry={nodes.lf_backtab.geometry}
            material={materials.backtab_01}
          />
          <mesh
            geometry={nodes.lf_backtab_logo.geometry}
            material={materials['default']}
          />
          <mesh
            geometry={nodes.lf_backtab_logo_air.geometry}
            material={materials['default']}
          />
          <mesh
            geometry={nodes.lf_dubrae.geometry}
            material={materials.dubrae_01}
          />
          <mesh
            geometry={nodes.lf_eyestay.geometry}
            material={materials.eyestay_01}
          />
          <mesh
            geometry={nodes.lf_eyestay_emb.geometry}
            material={materials.eyestay_01}
          />
          <mesh
            geometry={nodes.lf_foxing.geometry}
            material={materials.foxing_01}
          />
          <mesh
            geometry={nodes.lf_interior_lining.geometry}
            material={materials['default']}
          />
          <mesh
            geometry={nodes.lf_lace.geometry}
            material={materials['default']}
          />
          <mesh
            geometry={nodes.lf_lining.geometry}
            material={materials['default']}
          />
          <mesh
            geometry={nodes.lf_quarter.geometry}
            material={materials.quarter_01}
          />
          <mesh
            geometry={nodes.lf_sockliner_topcloth.geometry}
            material={materials['default']}
          />
          <mesh
            geometry={nodes.lf_sockliner_topcloth_logo.geometry}
            material={materials['default']}
          />
          <mesh
            geometry={nodes.lf_swoosh.geometry}
            material={materials.swoosh_01}
          />
          <mesh geometry={nodes.lf_tip.geometry} material={materials.tip_01} />
          <mesh
            geometry={nodes.lf_tongue.geometry}
            material={materials.tongue_01}
          />
          <mesh
            geometry={nodes.lf_tongue_binding.geometry}
            material={materials['default']}
          />
          <mesh
            geometry={nodes.lf_tongue_label.geometry}
            material={materials['default']}
          />
          <mesh
            geometry={nodes.lf_tongue_label_logo.geometry}
            material={materials['default']}
          />
          <mesh
            geometry={nodes.lf_tongue_lining.geometry}
            material={materials['default']}
          />
          <mesh
            geometry={nodes.lf_vamp.geometry}
            material={materials.vamp_01}
          />
          <mesh
            geometry={nodes.lf_backtab_pid.geometry}
            material={materials.pid}
          />
          <mesh
            geometry={nodes.lf_backstay_stitch.geometry}
            material={materials.stitch_01}
          />
          <mesh
            geometry={nodes.lf_backtab_stitch.geometry}
            material={materials.stitch_01}
          />
          <mesh
            geometry={nodes.lf_eyestay_stitch.geometry}
            material={materials.stitch_01}
          />
          <mesh
            geometry={nodes.lf_foxing_stitch.geometry}
            material={materials.stitch_01}
          />
          <mesh
            geometry={nodes.lf_swoosh_stitch.geometry}
            material={materials.stitch_01}
          />
          <mesh
            geometry={nodes.lf_tip_stitch.geometry}
            material={materials.stitch_01}
          />
          <mesh
            geometry={nodes.lf_tongue_binding_stitch.geometry}
            material={materials.stitch_01}
          />
          <mesh
            geometry={nodes.lf_tongue_lining_stitch.geometry}
            material={materials.stitch_01}
          />
          <mesh
            geometry={nodes.lf_tongue_stitch.geometry}
            material={materials.stitch_01}
          />
          <mesh
            geometry={nodes.lf_airbag.geometry}
            material={materials.midsole_01}
          />
          <mesh
            geometry={nodes.lf_midsole.geometry}
            material={materials.midsole_01}
          />
          <mesh
            geometry={nodes.lf_midsole_accent.geometry}
            material={materials.lowpoly}
          />
          <mesh
            geometry={nodes.lf_midsole_stitch.geometry}
            material={materials.midsole_01}
          />
          <mesh
            geometry={nodes.lf_outsole.geometry}
            material={materials.outsole_01}
          />
          <mesh
            geometry={nodes.lf_outsole_nike.geometry}
            material={materials.lowpoly}
          />
        </group>
        <group position={[-0.75, 0.75, -0.55]} rotation={[0, -0.262, 0]}>
          <mesh
            geometry={nodes.rt_backstay.geometry}
            material={materials.backtab_01}
          />
          <mesh
            geometry={nodes.rt_backtab.geometry}
            material={materials.backtab_01}
          />
          <mesh
            geometry={nodes.rt_backtab_logo.geometry}
            material={materials['default']}
          />
          <mesh
            geometry={nodes.rt_backtab_logo_air.geometry}
            material={materials['default']}
          />
          <mesh
            geometry={nodes.rt_dubrae.geometry}
            material={materials.dubrae_01}
          />
          <mesh
            geometry={nodes.rt_eyestay.geometry}
            material={materials.eyestay_01}
          />
          <mesh
            geometry={nodes.rt_eyestay_emb.geometry}
            material={materials.eyestay_01}
          />
          <mesh
            geometry={nodes.rt_foxing.geometry}
            material={materials.foxing_01}
          />
          <mesh
            geometry={nodes.rt_interior_lining.geometry}
            material={materials['default']}
          />
          <mesh
            geometry={nodes.rt_lace.geometry}
            material={materials['default']}
          />
          <mesh
            geometry={nodes.rt_lining.geometry}
            material={materials['default']}
          />
          <mesh
            geometry={nodes.rt_quarter.geometry}
            material={materials.quarter_01}
          />
          <mesh
            geometry={nodes.rt_sockliner_topcloth.geometry}
            material={materials['default']}
          />
          <mesh
            geometry={nodes.rt_sockliner_topcloth_logo.geometry}
            material={materials['default']}
          />
          <mesh
            geometry={nodes.rt_swoosh.geometry}
            material={materials.swoosh_01}
          />
          <mesh geometry={nodes.rt_tip.geometry} material={materials.tip_01} />
          <mesh
            geometry={nodes.rt_tongue.geometry}
            material={materials.tongue_01}
          />
          <mesh
            geometry={nodes.rt_tongue_binding.geometry}
            material={materials['default']}
          />
          <mesh
            geometry={nodes.rt_tongue_label.geometry}
            material={materials['default']}
          />
          <mesh
            geometry={nodes.rt_tongue_label_logo.geometry}
            material={materials['default']}
          />
          <mesh
            geometry={nodes.rt_tongue_lining.geometry}
            material={materials['default']}
          />
          <mesh
            geometry={nodes.rt_vamp.geometry}
            material={materials.vamp_01}
          />
          <mesh
            geometry={nodes.rt_backtab_pid.geometry}
            material={materials.pid}
          />
          <mesh
            geometry={nodes.rt_backstay_stitch.geometry}
            material={materials.stitch_01}
          />
          <mesh
            geometry={nodes.rt_backtab_stitch.geometry}
            material={materials.stitch_01}
          />
          <mesh
            geometry={nodes.rt_eyestay_stitch.geometry}
            material={materials.stitch_01}
          />
          <mesh
            geometry={nodes.rt_foxing_stitch.geometry}
            material={materials.stitch_01}
          />
          <mesh
            geometry={nodes.rt_swoosh_stitch.geometry}
            material={materials.stitch_01}
          />
          <mesh
            geometry={nodes.rt_tip_stitch.geometry}
            material={materials.stitch_01}
          />
          <mesh
            geometry={nodes.rt_tongue_binding_stitch.geometry}
            material={materials.stitch_01}
          />
          <mesh
            geometry={nodes.rt_tongue_lining_stitch.geometry}
            material={materials.stitch_01}
          />
          <mesh
            geometry={nodes.rt_tongue_stitch.geometry}
            material={materials.stitch_01}
          />
          <mesh
            geometry={nodes.rt_airbag.geometry}
            material={materials.midsole_01}
          />
          <mesh
            geometry={nodes.rt_midsole.geometry}
            material={materials.midsole_01}
          />
          <mesh
            geometry={nodes.rt_midsole_accent.geometry}
            material={materials.midsole_01}
          />
          <mesh
            geometry={nodes.rt_midsole_stitch.geometry}
            material={materials.midsole_01}
          />
          <mesh
            geometry={nodes.rt_outsole.geometry}
            material={materials.outsole_01}
          />
          <mesh
            geometry={nodes.rt_outsole_nike.geometry}
            material={materials.outsole_01}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/AF1_v2.glb');
